add jmeter tests in pipeline

diff --git a/.github/workflows/palate-deploy.yml b/.github/workflows/palate-deploy.yml
--- a/.github/workflows/palate-deploy.yml
+++ b/.github/workflows/palate-deploy.yml
@@ -86,7 +86,7 @@ jobs:
         docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
         docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
         echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
-
+  
     - name: Update ECS for new Image
       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -118,3 +118,45 @@ jobs:
         fi
 
         aws ecs update-service --service $ECS_SERVICE --cluster $ECS_CLUSTER --force-new-deployment
+        aws ecs wait services-stable --services $ECS_SERVICE --cluster $ECS_CLUSTER
+        
+    - name: Checkout main branch
+      uses: actions/checkout@v3
+      with:
+        ref: refs/heads/main
+        repository: Palatepower77/palate-app-infrastructure
+        token: ${{ secrets.GIT_TOKEN }}
+    
+    - name: JMeter Test Execution
+      run: |
+          echo 'Download JMeter'
+          wget -O jmeter.tgz https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.5.tgz
+          tar -xzf jmeter.tgz
+    
+          echo 'Run JMeter Test'
+          ./apache-jmeter-5.5/bin/jmeter -JTOKEN=${{ secrets.TOKEN }} -n -t Palate_App.jmx -l result.jtl > jmeter_output.log
+          echo "$(cat jmeter_output.log)"
+    
+          echo 'Convert JTL to CSV'
+          sed -e 's/<[^>]*>//g' result.jtl > result.csv
+          
+    - name: Upload Result Files as Artifacts
+      uses: actions/upload-artifact@v2
+      with:
+          name: JMeter Result
+          path: |
+            result.csv
+            result.jtl
+            
+    - name: Check Result Errors
+      run: |
+          jmeter_output=$(cat jmeter_output.log)
+          summary=$(echo "$jmeter_output" | grep -o "summary +.*")
+          while read -r line; do
+            error_count=$(echo "$line" | grep -o "Err: *[0-9]*" | awk -F' ' '{print $NF}')
+            if [ "$error_count" -gt 0 ]; then
+              echo "There were errors in the JMeter result"
+              exit 1
+            fi
+          done <<< "$summary"
+          echo "No errors found in the JMeter result"
